import 'package:flutter/material.dart';

abstract class AppColors {
  static const Color hintColor = Color(0xffC4C4C4);
  static const Color dividerColor = Color(0xffC4C4C4);
  static const Color canvasColor = Color(0xfffdfdfd);
  static const Color backgroundColor = Color(0xffFFFFFF);
  static const Color highlightColor = Color(0x1A31B768);
  static const Color disabledColor = Color(0xff919191);
  static const Color primaryColor = Color(0xffFFFFFF);
  static const Color indicatorColor = Color(0xff31B768);
  static const Color progressValueColor = Color(0xff31B768);
  static const Color progressBackgroundColor = Color(0xfffdfdfd);
  static const Color buttonColor = Color(0xff31B768);
  static const Color iconColor = Color(0xff31B768);
  static const Color accentColor = Color(0xffFFFFFF);
  static const Color errorColor = Color(0xffC60000);
  static const Color warningColor = Color(0xffffbb33);
  static const Color scrollTrackColor = Color(0xffC4C4C4);
  static const Color dragLineColor = Color(0xffC4C4C4);
  static const Color bottomAppBarColor = Color(0xffC4C4C4);
  static const Color inputFillColor = Color(0xffF6F6F6);
  static const Color inputNormalBorderColor = Color(0x4D31B768);
  static const Color inputFocusBorderColor = Color(0xff31B768);
  static const Color cardColor = Color(0xffC4C4C4);
  static const Color cardShadowColor = Color(0x99000000);
  static const Color buttonTextColor = Color(0xffFFFFFF);
  static const Color headLineTextColor = Color(0xff555A60);
  static const Color toolBarTitleColor = Color(0xff555A60);
  static const Color captionTextColor = Color(0xff555A60);
  static const Color bodyTextColor = Color(0x99808481);
  static const Color subtitleTextColor = Color(0x99808481);
  static const Color scaffoldBackgroundColor = Colors.white;
  static const Color modalBackgroundColor = Color(0x427C7C7C);
  static const Color cursorColor = Color(0xff31B768);
  static const Color textSelectionHandlerColor = Color(0xff31B768);
  static const Color backgroundPaintColor = Color(0xff31B768);
  static const Color textSelectionColor = Color(0x4D31B768);
  static const Color shadowColor = Color(0xFF404040);
  static const Color shimmerColor = Color(0xffeeeeee);
}
